package com.sid.tutorials.java.apache.spark.app;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.HashSet;
import java.util.Set;

/**
 * A wrapper for an input file containing a list of what we think are "boring" words.
 * <p>
 * The list was generated by running a word count across all of VirtualPairProgrammer's subtitle files.
 * <p>
 * Words that appear in every single course must (we think) be "boring" - ie they don't have a relevance
 * to just one specific course.
 * <p>
 * This list of words is "small data" - ie it can be safely loaded into the driver's JVM - no need to
 * distribute this data.
 */
public class Util {
    public static Set<String> borings = new HashSet<String>();

    static {
    /*  On the video, I say "change this class name" - ignore that.
        The class name should have been Util, as it is here!
     */

    /*  Load the resource from the classpath. Be defensive: getResourceAsStream can return null
        (for example when running from an IDE/run configuration where resources aren't on the classpath).*/
    InputStream is = Util.class.getResourceAsStream("/subtitles/boringwords.txt");
    if (is == null) {
      System.err.println("Warning: '/subtitles/boringwords.txt' not found on classpath - continuing with empty boring-words set.");
    } else {
      try (BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
        br.lines()
          .map(String::trim)
          .filter(s -> !s.isEmpty())
          .forEach(borings::add);
      } catch (Exception e) {
        throw new RuntimeException("Failed to load boring words resource", e);
      }
    }
    }

    /**
     * Returns true if we think the word is "boring" - ie it doesn't seem to be a keyword
     * for a training course.
     */
    public static boolean isBoring(String word) {
        return borings.contains(word);
    }

    /**
     * Convenience method for more readable client code
     */
    public static boolean isNotBoring(String word) {
        return !isBoring(word);
    }

}
